--lua-init=@C:\Uygulamalar\zapret2-v1.0.1\lua\zapret-lib.lua
--lua-init=@C:\Uygulamalar\zapret2-v1.0.1\lua\zapret-antidpi.lua
--wf-tcp-out=80,443
--ipset-ip=128.116.0.0/16,18.244.87.0/24,52.222.236.0/24,99.84.91.0/24,184.25.88.0/24
--payload=tls_client_hello
--lua-desync=fake:blob=0x00000000:tcp_md5:repeats=1
--lua-desync=fake:blob=fake_default_tls:tcp_md5:tls_mod=rnd,dupsid:repeats=1
--lua-desync=multisplit:pos=2
